alias gb="git branch -vva"
alias gl="git log --oneline --all --decorate --graph --date=short --pretty=format:'%C(178)%h %C(88)%ad %C(27)%G? %C(64)%aN  %C(auto)%d %n  %C(255)%<(72,trunc)%s' -10"
alias gn="git show --format=fuller --name-status --show-signature"
alias gs="git status -b --show-stash -s"
alias gdd="git difftool --tool=vimdiff --no-prompt --trust-exit-code"
alias gm="git diff --name-only --diff-filter=U"
alias gmm="git mergetool --tool=diffconflicts --no-prompt"
